### ISSUE TITLE
threshold count should be based on consent:yes >= 5

### ISSUE THREAD

**Issue by andrewsu** [andrewsu/mentorship-survey-analysis#4]
Currently, reports are generated if the number of respondents is >= 5.  Let's modify so that this threshold is based on the number of respondents answering "yes" to `Q0:Do you consent to taking this survey?` being >= 5

**Comment by rjawesome** [comment]
Would we just want to throw out rows when consent is not "yes", or still keep them in the aggregate data then?

**Comment by andrewsu** [comment]
I think for the few examples I saw it seemed like if the answer to that question was no, then their answers for all other questions was empty. But regardless, I think it would be good to just remove those entire survey responses up front...

**Comment by andrewsu** [comment]
close as complete with #9
