### ISSUE TITLE
change overflow behavior for free text answers

### ISSUE THREAD

**Issue by andrewsu** [andrewsu/mentorship-survey-analysis#5]
Currently, long free-text answers are truncated using `...` (see red arrows below).  Also, the overall number of free-text answers is truncated with `...` (see green arrow below).  We want to change this so that all answers are shown in their entirety.
 
![image](https://github.com/andrewsu/mentorship-survey-analysis/assets/2635409/a1825d43-89a9-4926-85ec-c9be83a557e2)

**Comment by rjawesome** [comment]
If all the answers wouldn't fit in one page, should a new page be created?

**Comment by andrewsu** [comment]
Yes, create as many pages as needed

**Comment by andrewsu** [comment]
close as complete with #9
